uploads = []
generated = []

[[outputs]]
id = "dW_VcmB0i3D68EfsKd5EV"
uri = "file://Manuel_Utilisateur_SOMELEC.pdf"
type = "pdf"
title = "Manuel_Utilisateur_SOMELEC.pdf (version actuelle)"

[[outputs]]
id = "d6fwizFC6OtYrcpXKmjoi"
uri = "file://Manuel_Utilisateur_SOMELEC.md"
type = "text"
title = "Manuel Utilisateur — SOMELEC Plans d'Action"

[[outputs]]
id = "IZHGuJUM6yXBrk1u_WOUj"
uri = "file://NOTE_PROCEDURE_UTILISATION.md"
type = "text"
title = "Note de Procédure — SOMELEC Gestion des Plans d'Action"

[[outputs]]
id = "VurhjX8GPXvxihWdPee51"
uri = "file://Manuel_Utilisateur_SOMELEC.docx"
type = "word_document"
title = "Guide Utilisateur SOMELEC — Version 2.0 (Juin 2026)"
